CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE public."Users" (
    "UserID" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserID")
);

CREATE TABLE public."Addresses" (
    "AddressID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Street" character varying(100) NOT NULL,
    "City" character varying(50) NOT NULL,
    "PostalCode" character varying(20) NOT NULL,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("AddressID")
);

CREATE TABLE public."Providers" (
    "ProviderID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProviderName" character varying(100) NOT NULL,
    "ContactPerson" character varying(50) NOT NULL,
    "PhoneNumber" text NOT NULL,
    "Email" text NOT NULL,
    CONSTRAINT "PK_Providers" PRIMARY KEY ("ProviderID")
);

CREATE TABLE public."Services" (
    "ServiceID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ServiceName" character varying(100) NOT NULL,
    "UnitOfMeasure" character varying(20) NOT NULL,
    CONSTRAINT "PK_Services" PRIMARY KEY ("ServiceID")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251129175943_BaseEntities', '8.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE public."Contracts" (
    "ContractID" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserID" integer NOT NULL,
    "AddressID" integer NOT NULL,
    "ServiceID" integer NOT NULL,
    "ProviderID" integer NOT NULL,
    "ContractNumber" character varying(50) NOT NULL,
    "ContractStartDate" timestamp with time zone NOT NULL,
    "ContractEndDate" timestamp with time zone,
    CONSTRAINT "PK_Contracts" PRIMARY KEY ("ContractID"),
    CONSTRAINT "FK_Contracts_Users_UserID" FOREIGN KEY ("UserID") REFERENCES public."Users" ("UserID") ON DELETE CASCADE,
    CONSTRAINT "FK_Contracts_Addresses_AddressID" FOREIGN KEY ("AddressID") REFERENCES public."Addresses" ("AddressID") ON DELETE CASCADE,
    CONSTRAINT "FK_Contracts_Services_ServiceID" FOREIGN KEY ("ServiceID") REFERENCES public."Services" ("ServiceID") ON DELETE CASCADE,
    CONSTRAINT "FK_Contracts_Providers_ProviderID" FOREIGN KEY ("ProviderID") REFERENCES public."Providers" ("ProviderID") ON DELETE CASCADE
);

CREATE INDEX "IX_Contracts_UserID" ON public."Contracts" ("UserID");

CREATE INDEX "IX_Contracts_AddressID" ON public."Contracts" ("AddressID");

CREATE INDEX "IX_Contracts_ServiceID" ON public."Contracts" ("ServiceID");

CREATE INDEX "IX_Contracts_ProviderID" ON public."Contracts" ("ProviderID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251129183039_Contracts', '8.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE public."Invoices" (
    "InvoiceID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ContractID" integer NOT NULL,
    "InvoiceDate" timestamp with time zone NOT NULL,
    "DueDate" timestamp with time zone NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "IsPaid" boolean NOT NULL,
    "PaymentDate" timestamp with time zone,
    CONSTRAINT "PK_Invoices" PRIMARY KEY ("InvoiceID"),
    CONSTRAINT "FK_Invoices_Contracts_ContractID" FOREIGN KEY ("ContractID") REFERENCES public."Contracts" ("ContractID") ON DELETE CASCADE
);

CREATE TABLE public."Payments" (
    "PaymentID" integer GENERATED BY DEFAULT AS IDENTITY,
    "InvoiceID" integer NOT NULL,
    "PaymentDate" timestamp with time zone NOT NULL,
    "PaymentAmount" numeric NOT NULL,
    "PaymentMethod" character varying(30) NOT NULL,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("PaymentID"),
    CONSTRAINT "FK_Payments_Invoices_InvoiceID" FOREIGN KEY ("InvoiceID") REFERENCES public."Invoices" ("InvoiceID") ON DELETE CASCADE
);

CREATE TABLE public."Notifications" (
    "NotificationID" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserID" integer NOT NULL,
    "NotificationDate" timestamp with time zone NOT NULL,
    "NotificationType" character varying(20) NOT NULL,
    "NotificationText" character varying(200) NOT NULL,
    "IsRead" boolean NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("NotificationID"),
    CONSTRAINT "FK_Notifications_Users_UserID" FOREIGN KEY ("UserID") REFERENCES public."Users" ("UserID") ON DELETE CASCADE
);

CREATE TABLE public."UserAddresses" (
    "UserAddressID" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserID" integer NOT NULL,
    "AddressID" integer NOT NULL,
    "IsPrimary" boolean NOT NULL,
    CONSTRAINT "PK_UserAddresses" PRIMARY KEY ("UserAddressID"),
    CONSTRAINT "FK_UserAddresses_Users_UserID" FOREIGN KEY ("UserID") REFERENCES public."Users" ("UserID") ON DELETE CASCADE,
    CONSTRAINT "FK_UserAddresses_Addresses_AddressID" FOREIGN KEY ("AddressID") REFERENCES public."Addresses" ("AddressID") ON DELETE CASCADE
);

CREATE TABLE public."MeterReadings" (
    "ReadingID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ContractID" integer NOT NULL,
    "ReadingDate" timestamp with time zone NOT NULL,
    "ReadingValue" numeric NOT NULL,
    "SubmittedByUserID" integer,
    CONSTRAINT "PK_MeterReadings" PRIMARY KEY ("ReadingID"),
    CONSTRAINT "FK_MeterReadings_Contracts_ContractID" FOREIGN KEY ("ContractID") REFERENCES public."Contracts" ("ContractID") ON DELETE CASCADE,
    CONSTRAINT "FK_MeterReadings_Users_SubmittedByUserID" FOREIGN KEY ("SubmittedByUserID") REFERENCES public."Users" ("UserID")
);

CREATE INDEX "IX_Invoices_ContractID" ON public."Invoices" ("ContractID");

CREATE INDEX "IX_Payments_InvoiceID" ON public."Payments" ("InvoiceID");

CREATE INDEX "IX_Notifications_UserID" ON public."Notifications" ("UserID");

CREATE INDEX "IX_UserAddresses_UserID" ON public."UserAddresses" ("UserID");

CREATE INDEX "IX_UserAddresses_AddressID" ON public."UserAddresses" ("AddressID");

CREATE INDEX "IX_MeterReadings_ContractID" ON public."MeterReadings" ("ContractID");

CREATE INDEX "IX_MeterReadings_SubmittedByUserID" ON public."MeterReadings" ("SubmittedByUserID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251129183337_SecondaryEntities', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE public."Services" ADD "Price" numeric NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251203213535_AddPriceToService', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE public."Notifications" ADD "LastUpdatedDate" timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251204190921_AddLastUpdatedDateToMotifications', '8.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE public."NotificationHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NotificationID" integer NOT NULL,
    "ChangedBy" text NOT NULL,
    "ChangedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_NotificationHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NotificationHistory_Notifications_NotificationID" FOREIGN KEY ("NotificationID") REFERENCES public."Notifications" ("NotificationID") ON DELETE CASCADE
);

CREATE INDEX "IX_NotificationHistory_NotificationID" ON public."NotificationHistory" ("NotificationID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251204203104_AddNotificationHistory', '8.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251214185655_SyncUsers', '8.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251220201605_InitUtilities', '8.0.11');

COMMIT;

